/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugasbesar;
import java.math.BigInteger;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author dwiachmadmaulana
 */
public class PasswordManager extends javax.swing.JFrame {
    

    private boolean newdata;
    private final Koneksi koneksi = new Koneksi();
    /**
     * Creates new form PasswordManager
     */
    public PasswordManager() {
        initComponents();
        getData();
        newdata = true;
        
    }
    
    public static byte[] getSHA(String input) throws NoSuchAlgorithmException
	{
		// Static getInstance method is called with hashing SHA
		MessageDigest md = MessageDigest.getInstance("SHA-256");

		// digest() method called
		// to calculate message digest of an input
		// and return array of byte
		return md.digest(input.getBytes(StandardCharsets.UTF_8));
	}
    
    public static String toHexString(byte[] hash)
	{
		// Convert byte array into signum representation
		BigInteger number = new BigInteger(1, hash);

		// Convert message digest into hex value
		StringBuilder hexString = new StringBuilder(number.toString(16));

		// Pad with leading zeros
		while (hexString.length() < 64)
		{
			hexString.insert(0, '0');
		}

		return hexString.toString();
	}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        JL1 = new javax.swing.JLabel();
        JL2 = new javax.swing.JLabel();
        JL3 = new javax.swing.JLabel();
        JL4 = new javax.swing.JLabel();
        JL5 = new javax.swing.JLabel();
        JT1 = new javax.swing.JTextField();
        JT2 = new javax.swing.JTextField();
        JT3 = new javax.swing.JTextField();
        JT4 = new javax.swing.JPasswordField();
        JT5 = new javax.swing.JTextField();
        JBsav = new javax.swing.JButton();
        JBdel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        JBres = new javax.swing.JButton();
        JBex = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        jLabel1.setText("Password Manager");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 21, -1, -1));

        JL1.setText("Account Name");
        jPanel1.add(JL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 60, -1, -1));

        JL2.setText("Application");
        jPanel1.add(JL2, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 95, -1, -1));

        JL3.setText("Username");
        jPanel1.add(JL3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 130, -1, -1));

        JL4.setText("Password");
        jPanel1.add(JL4, new org.netbeans.lib.awtextra.AbsoluteConstraints(277, 130, -1, -1));

        JL5.setText("Description");
        jPanel1.add(JL5, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 165, -1, -1));
        jPanel1.add(JT1, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 57, 352, -1));
        jPanel1.add(JT2, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 92, 352, -1));
        jPanel1.add(JT3, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 127, 128, -1));
        jPanel1.add(JT4, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 127, 130, -1));
        jPanel1.add(JT5, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 162, 352, -1));

        JBsav.setBackground(new java.awt.Color(204, 255, 255));
        JBsav.setText("Save");
        JBsav.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsavActionPerformed(evt);
            }
        });
        jPanel1.add(JBsav, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        JBdel.setBackground(new java.awt.Color(204, 255, 255));
        JBdel.setText("Delete");
        JBdel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBdelActionPerformed(evt);
            }
        });
        jPanel1.add(JBdel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, -1, -1));

        tabel.setBackground(new java.awt.Color(204, 204, 204));
        tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Account Name", "Application", "Username", "Password", "Description"
            }
        ));
        tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabel);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 464, 155));

        jLabel7.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        jLabel7.setText("Account");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, -1, -1));

        JBres.setBackground(new java.awt.Color(204, 255, 255));
        JBres.setText("Reset");
        JBres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBresActionPerformed(evt);
            }
        });
        jPanel1.add(JBres, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 200, -1, -1));

        JBex.setBackground(new java.awt.Color(204, 255, 255));
        JBex.setText("Exit");
        JBex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBexActionPerformed(evt);
            }
        });
        jPanel1.add(JBex, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBsavActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsavActionPerformed
        // TODO add your handling code here:
       
        if(newdata){
            try {
                String S1 = JT4.getText();
                JT4.setText("\n" + toHexString(getSHA(S1)));
                String sql ="INSERT INTO PassMan VALUES ('%s','%s','%s','%s','%s')";
                
                sql = String.format(
                        sql,
                        JT1.getText(),
                        JT2.getText(),
                        JT3.getText(),
                        JT4.getText(),
                        JT5.getText()
                        
                );
                
                Connection cn = koneksi.getKoneksi();
                PreparedStatement pst = cn.prepareStatement(sql);
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "Berhasil Ditambahkan");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Gagal Ditambahkan"+ ex);
                Logger.getLogger(PasswordManager.class.getName()).log(Level.SEVERE, null, ex);
                
            } catch (NoSuchAlgorithmException ex) {
                Logger.getLogger(PasswordManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else{
            try{
                String sql ="UPDATE PassMan SET Application='%s',Username='%s',Password='%s',Description='%s' WHERE Account_Name='%s'";
                sql = String.format(
                        sql,
                        
                        JT2.getText(),
                        JT3.getText(),
                        JT4.getText(),
                        JT5.getText(),
                        JT1.getText()
                        
                );
                Connection cn = koneksi.getKoneksi();
                PreparedStatement pst = cn.prepareStatement(sql);
                
                pst.execute();
                JOptionPane.showMessageDialog(null, "Berhasil Update");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Gagal Update"+ ex);
                Logger.getLogger(PasswordManager.class.getName()).log(Level.SEVERE, null, ex);
                
            }
        }
        getData();
    }//GEN-LAST:event_JBsavActionPerformed

    private void tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelMouseClicked
        try {
            // TODO add your handling code here:
            newdata = false;
            
            int row = tabel.getSelectedRow();
            String Account_Name = tabel.getModel().getValueAt(row, 0).toString();
            
            Connection cn = koneksi.getKoneksi();
            Statement stm = cn.createStatement();
            ResultSet st = stm.executeQuery("SELECT * FROM PassMan WHERE Account_Name='"+Account_Name+"'");
            
            if(st.next()){
                JT1.setText(st.getString("Account_Name"));
                JT2.setText(st.getString("Application"));
                JT3.setText(st.getString("Username"));
                JT4.setText(st.getString("Password"));
                JT5.setText(st.getString("Description"));
                
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(PasswordManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tabelMouseClicked

    private void JBdelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBdelActionPerformed
        try {
            // TODO add your handling code here:
            String sql ="DELETE FROM PassMan WHERE Account_Name='"+JT1.getText()+"'";
            
            Connection cn =koneksi.getKoneksi();
            PreparedStatement pr = cn.prepareStatement(sql);
            
            pr.execute();
            JOptionPane.showMessageDialog(null, "Berhasil Delete");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Gagal Delete");
            Logger.getLogger(PasswordManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        getData();
    }//GEN-LAST:event_JBdelActionPerformed

    private void JBresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBresActionPerformed
        // TODO add your handling code here:
        JT1.setText(null);
        JT2.setText(null);
        JT3.setText(null);
        JT4.setText(null);
        JT5.setText(null);
    }//GEN-LAST:event_JBresActionPerformed

    private void JBexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBexActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_JBexActionPerformed

    private void getData(){
        try{
            Connection cn = koneksi.getKoneksi();
            Statement stm = cn.createStatement();
            ResultSet st = stm.executeQuery("SELECT * FROM PassMan");
            
            DefaultTableModel model = (DefaultTableModel) tabel.getModel();
            
            model.setRowCount(0);
            while(st.next()){
                String Account_Name = st.getString("Account_Name");
                String Application = st.getString("Application");
                String Username = st.getString("Username");
                String Password = st.getString("Password");
                String Description = st.getString("Description");
                
                model.addRow(new Object[]{Account_Name,Application,Username,Password,Description});
                
            }
    }   catch (SQLException ex) {
            Logger.getLogger(PasswordManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PasswordManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PasswordManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PasswordManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PasswordManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new PasswordManager().setVisible(true);
        });
          /* Plain-text password initialization. */  
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBdel;
    private javax.swing.JButton JBex;
    private javax.swing.JButton JBres;
    private javax.swing.JButton JBsav;
    private javax.swing.JLabel JL1;
    private javax.swing.JLabel JL2;
    private javax.swing.JLabel JL3;
    private javax.swing.JLabel JL4;
    private javax.swing.JLabel JL5;
    private javax.swing.JTextField JT1;
    private javax.swing.JTextField JT2;
    private javax.swing.JTextField JT3;
    private javax.swing.JPasswordField JT4;
    private javax.swing.JTextField JT5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabel;
    // End of variables declaration//GEN-END:variables
}
